version: 2.1
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - run: echo "A first hello"
  sally:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - run: echo "Double trouble"

workflows:
  version: 2.1
  bobby_sally:
    jobs:
      - bobby
      - sally
